import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const router = useRouter();

  useEffect(
    () =>
      document.addEventListener(
        "keypress",
        (e) => e.code === "KeyB" && e.ctrlKey && router.push("/users")
      ),
    []
  );

  return (
    <div>
      <Head>
        <title>User management system</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://media.istockphoto.com/vectors/user-icon-flat-isolated-on-white-background-user-symbol-vector-vector-id1300845620?k=20&m=1300845620&s=612x612&w=0&h=f4XTZDAv7NPuZbG0habSpU0sNgECM0X7nbKzTUta3n8="
        />
      </Head>

      <main className="container">
        <div className="center">
          <h2 className="hero"> Welcome to the user management system </h2>
          <p className="subHero">
            Click <span className="c-red"> ctrl + B </span> to open console{" "}
          </p>
        </div>
      </main>
    </div>
  );
}
